version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - 28647:80 # 접속에 사용할 port 수정   Where the first 28647 is the local port and the second 8080 is the container port.
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./video:/video # m3u8 파일이 위치하는 폴더
    container_name: test-nginx